# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target '2015-06-29-圆形渐变进度条' do

pod 'TKit', '~>1.1.2'
pod 'pop', '~>1.0.7'

end

target '2015-06-29-圆形渐变进度条Tests' do

end

